name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: TwitchChatAnswers-${{ runner.os }}.zip
        directory: bin/Release/net7.0/
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: '**/TwitchChatAnswers-${{ runner.os }}.zip'

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v3
    - name: Action For Semantic Release
      uses: cycjimmy/semantic-release-action@v4.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
